name: Update Fear and Greed Index

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggers

jobs:
  update-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch and update data
      run: |
        python - <<EOF
        import requests
        import csv
        import os

        # API URL to fetch the Fear and Greed Index
        url = "https://api.alternative.me/fng/?limit=1"
        response = requests.get(url)
        data = response.json()

        # Extract value and timestamp from the response
        value = data['data'][0]['value']
        timestamp = data['data'][0]['timestamp']

        # Prepare the new data as a list
        new_data = [timestamp, value]

        # Define the CSV file name
        csv_file = 'fear_and_greed.csv'
        file_exists = os.path.isfile(csv_file)

        # Write data to the CSV file
        with open(csv_file, mode='a', newline='') as f:
            writer = csv.writer(f)
            if not file_exists:
                writer.writerow(['timestamp', 'value'])  # Write header if the file is new
            writer.writerow(new_data)  # Write the new data

        # Create an output file to signal whether there was an update
        with open('output.txt', 'w') as f:
            f.write("UPDATED")
        EOF

    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        if [[ $(cat output.txt) == "UPDATED" ]]; then
          git add fear_and_greed.csv
          git commit -m "Update Fear and Greed Index"
          git push
        fi
